/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package connect.four.gui;

import java.awt.event.ActionEvent;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

import connect.four.Game;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class MainMenuPanel extends javax.swing.JPanel {

  private String name1;
  private String name2;
  GUI gui;
  private boolean isEnabled;
  
  private JButton butPlay;
  private JLabel playerName1Label;
  private JLabel playerName2Label;
  private JToggleButton jtComputerToggle;
  private JTextField tfplayer1;
  private JTextField tfplayer2;
  private JLabel title;
  private JButton play1;
  private JButton play2;
  
  private JLabel win1Label;
  private JLabel loss1Label;
  private JLabel win2Label;
  private JLabel loss2Label;
  private JLabel winCompLabel;
  private JLabel lossCompLabel;
  private JButton loadButton;
  
  /**
   * Main Menu constructor.
   * @param gui the gui object for the game.
   */
  public MainMenuPanel(GUI gui) {
    initComponents();
    setSize(1280,800);
    this.gui = gui;
    isEnabled = false;

    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the
   * form. WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {

    title = new JLabel();
    tfplayer1 = new JTextField();
    tfplayer2 = new JTextField();
    playerName1Label = new JLabel();
    playerName2Label = new JLabel();
    play1= new JButton();
    play2= new JButton();
    butPlay = new JButton();
    jtComputerToggle = new JToggleButton();
    
    win1Label = new JLabel();
    loss1Label = new JLabel();
    win2Label = new JLabel();
    loss2Label = new JLabel();
    winCompLabel = new JLabel();
    lossCompLabel = new JLabel();
    loadButton = new JButton();

    ButtonGroup group = new ButtonGroup();
    
    setBackground(new Color(0, 0, 0));

    title.setFont(new Font("Lucida Grande", 0, 48)); // NOI18N
    title.setForeground(new Color(255, 255, 255));
    title.setText("Connect Four");

    tfplayer1.setText("Player 1");
    tfplayer1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        tfplayer1ActionPerformed(evt);
      }
    });

    tfplayer2.setText("Player 2");
    tfplayer2.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        tfplayer2ActionPerformed(evt);
      }
    });

    playerName1Label.setFont(new Font("Lucida Grande", 0, 18));
    playerName1Label.setForeground(new Color(255, 255, 255));
    playerName1Label.setText("Player 1:");

    playerName2Label.setFont(new Font("Lucida Grande", 0, 18));
    playerName2Label.setForeground(new Color(255, 255, 255));
    playerName2Label.setText("Player 2:");
    
    play1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
    play1.setText("player 1 first");
    play1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        play1ActionPerformed(evt);
      }
      });

    play2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
    play2.setText("olay");
    play2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        play2ActionPerformed(evt);

      }
    });

    group.add(play1);
    group.add(play2);
    
    win1Label.setFont(new Font("Lucida Grande", 0, 18));
    win1Label.setForeground(new Color(255, 255, 255));
    win1Label.setText("Player 1 Wins:");
    
    loss1Label.setFont(new Font("Lucida Grande", 0, 18));
    loss1Label.setForeground(new Color(255, 255, 255));
    loss1Label.setText("Player 1 Losses:");
    
    win2Label.setFont(new Font("Lucida Grande", 0, 18));
    win2Label.setForeground(new Color(255, 255, 255));
    win2Label.setText("Player 2 Wins:");
    
    loss2Label.setFont(new Font("Lucida Grande", 0, 18));
    loss2Label.setForeground(new Color(255, 255, 255));
    loss2Label.setText("Player 2 Losses:");
    
    winCompLabel.setFont(new Font("Lucida Grande", 0, 18));
    winCompLabel.setForeground(new Color(255, 255, 255));
    winCompLabel.setText("Compputer Wins:");
    
    lossCompLabel.setFont(new Font("Lucida Grande", 0, 18));
    lossCompLabel.setForeground(new Color(255, 255, 255));
    lossCompLabel.setText("Computer Losses:");

    butPlay.setFont(new Font("Lucida Grande", 0, 36)); // NOI18N
    butPlay.setText("PLAY");
    butPlay.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        butPlayActionPerformed(evt);
      }
    });
    
    loadButton.setFont(new Font("Lucida Grande", 0, 36)); // NOI18N
    loadButton.setText("PLAY");
    loadButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        loadButtonActionPerformed(evt);
      }
    });

    jtComputerToggle.setFont(new Font("Lucida Grande", 0, 18)); // NOI18N
    jtComputerToggle.setText("Play Against Computer");
    jtComputerToggle.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jtComputerToggleActionPerformed(evt);
      }
    });

    GroupLayout layout = new GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(title)
            .addGap(471, 471, 471))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(playerName1Label)
                            .addGap(18, 18, 18)
                            .addComponent(tfplayer1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(playerName2Label)
                            .addGap(18, 18, 18)
                            .addComponent(tfplayer2, GroupLayout.PREFERRED_SIZE, 431, GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(524, 524, 524)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(butPlay, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(jtComputerToggle, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addContainerGap(379, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(title)
            .addGap(59, 59, 59)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(tfplayer1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addComponent(playerName1Label))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(tfplayer2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addComponent(playerName2Label))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jtComputerToggle, GroupLayout.PREFERRED_SIZE, 
                52, GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45)
            .addComponent(butPlay, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
            .addContainerGap(352, Short.MAX_VALUE)));
  }

  private void tfplayer2ActionPerformed(ActionEvent evt) {

  }

  private void tfplayer1ActionPerformed(ActionEvent evt) {

  }

  private void butPlayActionPerformed(ActionEvent evt) {
    gui.setPlayer1Name(tfplayer1.getText());
    gui.setPlayer2Name(tfplayer2.getText());
    //gui.game.start();
    gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();
  }
  
  private void play1ActionPerformed(ActionEvent evt) {
    if(!isEnabled) {
      play2.setEnabled(false);
      //play1.pla

    }else {
      play2.setEnabled(true);
    }
    //gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();

  }
  

  private void play2ActionPerformed(ActionEvent evt) {
    if(!isEnabled) {
      play1.setEnabled(false);


    }else
    {
      play2.setEnabled(true);

    }
    //gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();

  }
  
  private void loadButtonActionPerformed(ActionEvent evt) {
    gui.getOldProgress();
    
  }

  private void jtComputerToggleActionPerformed(ActionEvent evt) {
    if (!isEnabled) {
      tfplayer2.setText("Computer");
      tfplayer2.setEditable(false);
      isEnabled = true;
    } else {
      tfplayer2.setText("Player 2");
      tfplayer2.setEditable(true);
      isEnabled = false;
    }
  }

  public boolean getIsEnabled() {
    return isEnabled;
  }

}
