/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package connect.four.gui;

import java.awt.event.ActionEvent;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

import connect.four.Game;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class MainMenuPanel extends JPanel {

  private String name1;
  private String name2;
  GUI gui;
  private boolean isEnabled;
  
  private JButton butPlay;
  private JLabel playerName1Label;
  private JLabel playerName2Label;
  private JToggleButton jtComputerToggle;
  private JTextField tfplayer1;
  private JTextField tfplayer2;
  private JLabel title;
  private JButton play1;
  private JButton play2;
  
  private JLabel win1Label;
  private JLabel loss1Label;
  private JLabel win2Label;
  private JLabel loss2Label;
  private JLabel winCompLabel;
  private JLabel lossCompLabel;
  private JButton loadButton;
  
  /**
   * Main Menu constructor.
   * @param gui the gui object for the game.
   */
  public MainMenuPanel(GUI gui) {
    initComponents();
    setSize(1280,800);
    
    this.gui = gui;
    isEnabled = false;

    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the
   * form. WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {

    title = new JLabel();
    tfplayer1 = new JTextField();
    tfplayer2 = new JTextField();
    playerName1Label = new JLabel();
    playerName2Label = new JLabel();
    play1= new JButton();
    play2= new JButton();
    butPlay = new JButton();
    jtComputerToggle = new JToggleButton();
    
    win1Label = new JLabel();
    loss1Label = new JLabel();
    win2Label = new JLabel();
    loss2Label = new JLabel();
    winCompLabel = new JLabel();
    lossCompLabel = new JLabel();
    loadButton = new JButton();
    
    setBackground(new Color(0, 0, 0));

    title.setFont(new Font("Lucida Grande", 0, 48)); // NOI18N
    title.setForeground(new Color(255, 255, 255));
    title.setText("Connect Four");

    tfplayer1.setText("Player 1");

    tfplayer1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        tfplayer1ActionPerformed(evt);
      }
    });

    tfplayer2.setText("Player 2");

    tfplayer2.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        tfplayer2ActionPerformed(evt);
      }
    });

    playerName1Label.setFont(new Font("Lucida Grande", 0, 18));
    playerName1Label.setForeground(new Color(255, 255, 255));
    playerName1Label.setText("Player 1:");

    playerName2Label.setFont(new Font("Lucida Grande", 0, 18));
    playerName2Label.setForeground(new Color(255, 255, 255));
    playerName2Label.setText("Player 2:");
    
    play1.setFont(new Font("Lucida Grande", 0, 36)); // NOI18N
    play1.setText("Player 1 Start ");
    play1.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        play1ActionPerformed(evt);
      }
      });

    play2.setFont(new Font("Lucida Grande", 0, 36)); // NOI18N
    play2.setText("Player 2 Start");
    play2.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        play2ActionPerformed(evt);

      }
    });
    
    win1Label.setFont(new Font("Lucida Grande", 0, 18));
    win1Label.setForeground(new Color(255, 255, 255));
    win1Label.setText("Player 1 Wins:");
    
    loss1Label.setFont(new Font("Lucida Grande", 0, 18));
    loss1Label.setForeground(new Color(255, 255, 255));
    loss1Label.setText("Player 1 Losses:");
    
    win2Label.setFont(new Font("Lucida Grande", 0, 18));
    win2Label.setForeground(new Color(255, 255, 255));
    win2Label.setText("Player 2 Wins:");
    
    loss2Label.setFont(new Font("Lucida Grande", 0, 18));
    loss2Label.setForeground(new Color(255, 255, 255));
    loss2Label.setText("Player 2 Losses:");
    
    winCompLabel.setFont(new Font("Lucida Grande", 0, 18));
    winCompLabel.setForeground(new Color(255, 255, 255));
    winCompLabel.setText("Compputer Wins:");
    
    lossCompLabel.setFont(new Font("Lucida Grande", 0, 18));
    lossCompLabel.setForeground(new Color(255, 255, 255));
    lossCompLabel.setText("Computer Losses:");

    butPlay.setFont(new Font("Lucida Grande", 0, 36));
    butPlay.setText("Random Player Starts");
    butPlay.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        butPlayActionPerformed(evt);
      }
    });
    
    loadButton.setFont(new Font("Lucida Grande", 0, 36));
    loadButton.setText("Load Last Game");
    loadButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        loadButtonActionPerformed(evt);
      }
    });

    jtComputerToggle.setFont(new Font("Lucida Grande", 0, 18));
    jtComputerToggle.setText("Play Against Computer");
    jtComputerToggle.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        jtComputerToggleActionPerformed(evt);
      }
    });
 
    JPanel playerPanel = new JPanel();
    JPanel titlePanel = new JPanel();
    JPanel scorePanel = new JPanel();
    JPanel buttonPanel = new JPanel();
    
    playerPanel.setSize(100, 100);
    
    initPlayerPanel(playerPanel);
    initTitlePanel(titlePanel);
    initScorePanel(scorePanel);
    initButtonPanel(buttonPanel);
    
    this.add(titlePanel, BorderLayout.NORTH);
    this.add(playerPanel, BorderLayout.CENTER);
    this.add(scorePanel, BorderLayout.EAST);
    this.add(buttonPanel, BorderLayout.SOUTH);
    
  }

  private void initPlayerPanel(JPanel panel) {
    GroupLayout layout = new GroupLayout(panel);

    JComponent contentPane = new JPanel(new BorderLayout(), true); 
    contentPane.setLayout(layout);  
    layout.setAutoCreateGaps(false);
    layout.setAutoCreateContainerGaps(false);
    
    GroupLayout.SequentialGroup horizontalLayout = layout.createSequentialGroup();  
    GroupLayout.SequentialGroup verticalLayout = layout.createSequentialGroup();
    
    //Horizontal Group Layout Setup
    //Add components to column 1
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(playerName1Label)
        .addComponent(playerName2Label));      
    //Main Middle column 2
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(tfplayer1)
        .addComponent(tfplayer2));
    //Play button column 3
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(play1)
        .addComponent(play2));   
    layout.setHorizontalGroup(horizontalLayout);
    
    //Add components to row 1
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(playerName1Label)
        .addComponent(tfplayer1)
        .addComponent(play1)); 
  //Add components to row 2
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(playerName2Label)
        .addComponent(tfplayer2)
        .addComponent(play2));           
    layout.setVerticalGroup(verticalLayout);
  }
  
  private void initTitlePanel(JPanel panel) {
    GroupLayout layout = new GroupLayout(panel);

    JComponent contentPane = new JPanel(new BorderLayout(), true); 
    contentPane.setLayout(layout);  
    layout.setAutoCreateGaps(false);
    layout.setAutoCreateContainerGaps(false);
    
    GroupLayout.SequentialGroup horizontalLayout = layout.createSequentialGroup();  
    GroupLayout.SequentialGroup verticalLayout = layout.createSequentialGroup();
    
    //Horizontal Group Layout Setup
    //Add components to column 1
    horizontalLayout.addGroup(layout.createParallelGroup()        
        .addComponent(title));        
    layout.setHorizontalGroup(horizontalLayout);
    
    //Vertical Group Layout Setup
    //Add components to row 1
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(title ));
    layout.setVerticalGroup(verticalLayout);
  }
  
  private void initScorePanel(JPanel panel) {
    GroupLayout layout = new GroupLayout(panel);

    JComponent contentPane = new JPanel(new BorderLayout(), true); 
    contentPane.setLayout(layout);  
    layout.setAutoCreateGaps(false);
    layout.setAutoCreateContainerGaps(false);
    
    GroupLayout.SequentialGroup horizontalLayout = layout.createSequentialGroup();  
    GroupLayout.SequentialGroup verticalLayout = layout.createSequentialGroup();
    
    //Horizontal Group Layout Setup
    //Add components to column 
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(win1Label)
        .addGap(10, 10, 10)
        .addComponent(loss1Label)
        .addGap(10, 10, 10)
        .addComponent(win2Label)
        .addGap(10, 10, 10)
        .addComponent(loss2Label)
        .addGap(10, 10, 10)
        .addComponent(winCompLabel)
        .addGap(10, 10, 10)
        .addComponent(lossCompLabel));        
    layout.setHorizontalGroup(horizontalLayout);
    
    //Vertical Group Layout Setup
    //Add components to row 1
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(win1Label));   
    //Add components to row 2
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(loss1Label));    
  //Add components to row 3
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(win2Label));        
    //Add components to row 4
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(loss2Label));    
    //Add Empty row to row 5
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(winCompLabel));        
    //Add components to row 6
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(lossCompLabel));         
    layout.setVerticalGroup(verticalLayout);
  }
  
  private void initButtonPanel(JPanel panel) {
    GroupLayout layout = new GroupLayout(panel);

    JComponent contentPane = new JPanel(new BorderLayout(), true); 
    contentPane.setLayout(layout);  
    layout.setAutoCreateGaps(false);
    layout.setAutoCreateContainerGaps(false);
    
    GroupLayout.SequentialGroup horizontalLayout = layout.createSequentialGroup();  
    GroupLayout.SequentialGroup verticalLayout = layout.createSequentialGroup();
    
    //Horizontal Group Layout Setup
    //Add components to column 
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(jtComputerToggle));    
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(loadButton));
    horizontalLayout.addGroup(layout.createParallelGroup()
        .addComponent(butPlay));           
    layout.setHorizontalGroup(horizontalLayout);
    
    //Vertical Group Layout Setup
    //Add components to row 1    
    verticalLayout.addGroup(layout.createParallelGroup()
        .addComponent(jtComputerToggle)
        .addComponent(loadButton)
        .addComponent(butPlay));               
    layout.setVerticalGroup(verticalLayout);
  }
  
  private void tfplayer2ActionPerformed(ActionEvent evt) {

  }

  private void tfplayer1ActionPerformed(ActionEvent evt) {

  }

  private void butPlayActionPerformed(ActionEvent evt) {
    gui.setPlayer1Name(tfplayer1.getText());
    gui.setPlayer2Name(tfplayer2.getText());
    //gui.game.start();
    gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();
  }
  
  private void play1ActionPerformed(ActionEvent evt) {
    if (!isEnabled) {
      play2.setEnabled(false);
      //play1.pla

    } else {
      play2.setEnabled(true);
    }
    //gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();

  }
  

  private void play2ActionPerformed(ActionEvent evt) {
    if (!isEnabled) {
      play1.setEnabled(false);


    } else {
      play2.setEnabled(true);

    }
    //gui.remove(this);
    gui.addGamePanel();
    gui.updateDisplay();

  }
  
  private void loadButtonActionPerformed(ActionEvent evt) {
    gui.getOldProgress();
    
  }

  private void jtComputerToggleActionPerformed(ActionEvent evt) {
    if (!isEnabled) {
      tfplayer2.setText("Computer");
      jtComputerToggle.setText("Play Against Player  ");
      tfplayer2.setEditable(false);
      isEnabled = true;
    } else {
      tfplayer2.setText("Player 2");
      jtComputerToggle.setText("Play Against Computer");
      tfplayer2.setEditable(true);
      isEnabled = false;
    }
  }

  public boolean getIsEnabled() {
    return isEnabled;
  }

}
